---
- name: Set up Munge on Master Node
  hosts: master
  become: true
  tasks:
    - name: Install Munge
      # Your installation tasks here (e.g., yum, apt)

    - name: Generate Munge Key
      command: /usr/sbin/create-munge-key -r
      args:
        creates: /etc/munge/munge.key

    - name: Ensure Munge is started and enabled
      service:
        name: munge
        state: started
        enabled: true
    - name: Configure PAM for Flux
      blockinfile:
        path: /etc/pam.d/flux
        block: |
          auth    required pam_localuser.so
          session required pam_limits.so

- name: Distribute Munge Key to Cluster Nodes
  hosts: flux_cluster
  become: true
  tasks:
    - name: Copy Munge Key from Master to Nodes
      copy:
        src: /etc/munge/munge.key
        dest: /etc/munge/munge.key
        owner: munge
        group: munge
        mode: '0400'
      when: inventory_hostname != groups['master'][0]

- name: Generate and Distribute Flux Network Certificate
  hosts: master
  become: true
  tasks:
    - name: Generate Flux Network Certificate
      command: sudo -u flux flux keygen /tmp/curve.cert
      args:
        creates: /tmp/curve.cert

    - name: Move Certificate to Proper Location
      copy:
        src: /tmp/curve.cert
        dest: /etc/flux/system/curve.cert
        owner: flux
        group: flux
        mode: '0400'

- name: Distribute Flux Network Certificate to Cluster Nodes
  hosts: flux_cluster
  become: true
  tasks:
    - name: Copy Flux Network Certificate to Node
      copy:
        src: /etc/flux/system/curve.cert
        dest: /etc/flux/system/curve.cert
        owner: flux
        group: flux
        mode: '0400'
      when: inventory_hostname != groups['master'][0]

- name: Collect Node Configuration Data
  hosts: flux_cluster
  become: true
  tasks:
    - name: Copy and Execute C Program
      script: /path/to/c-program
      register: node_config

    - name: Save Node Configuration to File
      copy:
        content: "{{ node_config.stdout }}"
        dest: "/tmp/node-{{ ansible_hostname }}-config.txt"

- name: Aggregate Configuration on Master Node
  hosts: master
  become: true
  tasks:
    - name: Fetch Configurations from Nodes
      fetch:
        src: "/tmp/node-{{ item }}-config.txt"
        dest: "/tmp/node-configs/"
        flat: yes
      loop: "{{ groups['flux_cluster'] }}"

    - name: Combine Node Configurations
      shell: cat /tmp/node-configs/* > /tmp/combined-node-configs.txt

- name: Update Flux Configuration
  hosts: master
  become: true
  tasks:
    - name: Update Flux Configuration File
      template:
        src: flux-config.j2
        dest: /etc/flux/system/conf.d/system.toml 
